FROM linuxbrew/linuxbrew

#RUN sudo apt-get install -y libssl-dev openssl bzip2
RUN sudo apt-get install -y python3 python3-pip
RUN python3 -m pip install --user virtualenv


#RUN 'export PATH="/home/linuxbrew/.linuxbrew/opt/python/libexec/bin:$PATH"' >> /home/linuxbrew/.bashrc
#RUN 'export PYTHONPATH=/home/linuxbrew/.linuxbrew/lib/python2.7/site-packages:$PYTHONPATH' >> /home/linuxbrew/.bashrc
#RUN 'export PYTHONPATH=/home/linuxbrew/.linuxbrew/lib/python3.5/site-packages:$PYTHONPATH' >> /home/linuxbrew/.bashrc

RUN brew install amber 
